version: '3'
services:
  db:
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scootertown
      POSTGRES_USER: scootertownadmin
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    restart: always
  integration:
    build: 
      context: .
      dockerfile: integration.Dockerfile
    depends_on:
      - db
      - api
    restart: always
